/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package showclixscanner.gui;

/**
 *
 * @author SunnyBat
 */
public class ApproveForm extends javax.swing.JFrame {
  
  private boolean approve;
  private java.util.concurrent.CountDownLatch countdown;

  /** Creates new form ApproveForm */
  public ApproveForm() {
    initComponents();
  }
  
  public ApproveForm(java.util.concurrent.CountDownLatch mCD) {
    initComponents();
    countdown = mCD;
  }
  
  public void setHeader(final String txt) {
    javax.swing.SwingUtilities.invokeLater(new Runnable() {
      @Override
      public void run() {
        jLabel1.setText(txt);
      }
    });
  }
  
  public void setDescription(final String txt) {
    javax.swing.SwingUtilities.invokeLater(new Runnable() {
      @Override
      public void run() {
        jTextArea1.setText(txt);
      }
    });
  }
  
  public void setApproveButtonText(final String txt) {
    javax.swing.SwingUtilities.invokeLater(new Runnable() {
      @Override
      public void run() {
        JBApprove.setText(txt);
      }
    });
  }
  
  public void setDisapproveButtonText(final String txt) {
    javax.swing.SwingUtilities.invokeLater(new Runnable() {
      @Override
      public void run() {
        JBDisapprove.setText(txt);
      }
    });
  }
  
  public boolean isApproved() {
    return approve;
  }
  
  private void setApprove(boolean b) {
    approve = b;
    setVisible(false);
    if (countdown != null) {
      countdown.countDown();
    }
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTextArea1 = new javax.swing.JTextArea();
    JBApprove = new javax.swing.JButton();
    JBDisapprove = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Approval Required");
    setAlwaysOnTop(true);

    jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Header");

    jTextArea1.setEditable(false);
    jTextArea1.setColumns(20);
    jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
    jTextArea1.setRows(5);
    jTextArea1.setText("Description");
    jScrollPane1.setViewportView(jTextArea1);

    JBApprove.setText("Approve");
    JBApprove.setToolTipText("");
    JBApprove.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        JBApproveActionPerformed(evt);
      }
    });

    JBDisapprove.setText("Disapprove");
    JBDisapprove.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        JBDisapproveActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jScrollPane1)
          .addGroup(layout.createSequentialGroup()
            .addComponent(JBApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(JBDisapprove, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(JBApprove)
          .addComponent(JBDisapprove))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void JBApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBApproveActionPerformed
    // TODO add your handling code here:
    setApprove(true);
  }//GEN-LAST:event_JBApproveActionPerformed

  private void JBDisapproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBDisapproveActionPerformed
    // TODO add your handling code here:
    setApprove(false);
  }//GEN-LAST:event_JBDisapproveActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton JBApprove;
  private javax.swing.JButton JBDisapprove;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextArea jTextArea1;
  // End of variables declaration//GEN-END:variables
}
