/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package showclixscanner.gui;

import java.io.File;
import javax.swing.JFileChooser;
import showclixscanner.Browser;
import showclixscanner.DatabaseManager;
import showclixscanner.Email;
import showclixscanner.ShowclixScanner;

/**
 *
 * @author SunnyBat
 */
public class Setup extends javax.swing.JFrame {

  private JFileChooser chooser = new JFileChooser();

  /** Creates new form Setup */
  public Setup() {
    initComponents();
    setCookieDirText(DatabaseManager.getDatabaseDirectory());
  }

  public void setCookieDirText(String directory) {
    String newStr = directory.substring(directory.length() / 5, directory.length());
    jLabel6.setText("..." + newStr.substring(newStr.indexOf("\\", 0), newStr.length()));
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jTextField1 = new javax.swing.JTextField();
    jPasswordField1 = new javax.swing.JPasswordField();
    jTextField2 = new javax.swing.JTextField();
    jButton1 = new javax.swing.JButton();
    JCBCarrier = new javax.swing.JComboBox();
    jLabel5 = new javax.swing.JLabel();
    jSlider1 = new javax.swing.JSlider();
    jCheckBox1 = new javax.swing.JCheckBox();
    jPanel1 = new javax.swing.JPanel();
    jLabel6 = new javax.swing.JLabel();
    jButton2 = new javax.swing.JButton();
    JCBEvent = new javax.swing.JComboBox();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setResizable(false);

    jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Showclix Scanner Setup");

    jLabel2.setText("Username:");

    jLabel3.setText("Password:");

    jLabel4.setText("Cell Num:");

    jButton1.setText("START!");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    JCBCarrier.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AT&T", "Sprint", "Verizon", "T-Mobile", "U.S. Cellular" }));

    jLabel5.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
    jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel5.setText("Time Between Refresh");

    jSlider1.setMajorTickSpacing(10);
    jSlider1.setMaximum(60);
    jSlider1.setMinorTickSpacing(5);
    jSlider1.setPaintLabels(true);
    jSlider1.setPaintTicks(true);
    jSlider1.setSnapToTicks(true);
    jSlider1.setValue(20);

    jCheckBox1.setSelected(true);
    jCheckBox1.setText("Automatically reserve tickets in Firefox (HOVER FOR WARNING!!!)");
    jCheckBox1.setToolTipText("<html>\nMake sure that you ONLY have Firefox<br>\nopen if you're right there working with it.<br>\nOtherwise, make sure it's COMPLETELY<br>\nclosed!<br>\n<i>The reason for this is:</i><br>\nIf Firefox doesn't close automatically<br>\n(if it prompts you if you really want to close<br>\nX tabs), the program will reserve tickets BUT<br>\nwill wait until Firefox is closed to open the PAX<br>\nregistration page.<br>\n<i>Also important to note:</i><br>\nFirefox should be set to your default web<br>\nbrowser. If not, you will have to manually<br>\nopen firefox (tickets will still be reserved<br>\nregardless of which browser is your default)\n</html>");
    jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jCheckBox1ActionPerformed(evt);
      }
    });

    jLabel6.setText("Firefox Cookies Directory");

    jButton2.setText("Change Cookies Directory");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addComponent(jLabel6)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jButton2))
    );

    JCBEvent.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PAX Prime", "PAX Aus" }));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel4)
              .addComponent(jLabel3)
              .addComponent(jLabel2))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
              .addComponent(jTextField1)
              .addComponent(jPasswordField1))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(JCBCarrier, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(JCBEvent, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
          .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jCheckBox1)
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(JCBEvent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(JCBCarrier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jLabel5)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jCheckBox1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(jButton1)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:
    Email.setUsername(jTextField1.getText());
    Email.setPassword(new String(jPasswordField1.getPassword()));
    Email.setCellNum(jTextField2.getText(), JCBCarrier.getSelectedItem().toString());
    ShowclixScanner.setRefreshTime(jSlider1.getValue());
    Browser.setKillFirefox(jCheckBox1.isSelected());
    int showclixID;
    if (JCBEvent.getSelectedItem().toString().equals("PAX Aus")) {
      showclixID = ShowclixScanner.AUS_SHOWCLIX_ID;
    } else {
      showclixID = ShowclixScanner.PRIME_SHOWCLIX_ID;
    }
    Browser.setShowclixLink(showclixID);
    ShowclixScanner.setShowclixURL(showclixID);
    dispose();
  }//GEN-LAST:event_jButton1ActionPerformed

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    // TODO add your handling code here:
    chooser.setCurrentDirectory(new java.io.File(System.getenv("APPDATA")));
    chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
    chooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("All Files", "sqlite"));
    final String reqSub = "Users\\" + System.getProperty("user.name") + "\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles";
    chooser.setFileFilter(new javax.swing.filechooser.FileFilter() {
      @Override // C:\Users\SunnyBat\AppData\Roaming
      public boolean accept(File f) {
        String name = f.getName().toLowerCase();
        String userSub;
        try {
          userSub = f.getAbsolutePath().substring(f.getAbsolutePath().toLowerCase().indexOf("users", 0));
          if (userSub.length() < 8) {
            userSub = "C:\\Users\\GoodName32481234";
          }
          userSub += "\\";
        } catch (Exception e) {
          try {
            if (f.getAbsolutePath().endsWith(":\\")) {
              return true;
            }
          } catch (Exception ef) {
          }
          userSub = "Not here, Unfortunately\\";
        }
        if (name.length() < 2) {
          return false;
        } else if (name.equals("users")
                || userSub.endsWith(System.getProperty("user.name") + "\\")
                || name.equals("appdata")
                || name.equals("roaming")
                || name.equals("mozilla")
                || name.equals("firefox")
                || name.equals("profiles")
                || name.equals("cookies.sqlite")) {
          return true;
        } else if (userSub.contains("\\Firefox\\Profiles")) {
          if (userSub.substring(0, userSub.lastIndexOf("\\") - 1).substring(0, userSub.substring(0, userSub.lastIndexOf("\\") - 1).lastIndexOf("\\")).equals(reqSub)) {
            return true;
          }
        }
        return false;
      }

      @Override
      public String getDescription() {
        return "Find For Me";
      }
    });
    chooser.setFileHidingEnabled(false);
    chooser.setAcceptAllFileFilterUsed(false);
    chooser.setDialogTitle("Select Firefox Cookie Database");
    chooser.setVisible(true);
    if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
      DatabaseManager.setDatabaseDirectory(chooser.getCurrentDirectory().getAbsolutePath());
      setCookieDirText(DatabaseManager.getDatabaseDirectory());
    } else {
      System.out.println("No Selection ");
    }
  }//GEN-LAST:event_jButton2ActionPerformed

  private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
    // TODO add your handling code here:
    jPanel1.setVisible(jCheckBox1.isSelected());
    pack();
  }//GEN-LAST:event_jCheckBox1ActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JComboBox JCBCarrier;
  private javax.swing.JComboBox JCBEvent;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JCheckBox jCheckBox1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPasswordField jPasswordField1;
  private javax.swing.JSlider jSlider1;
  private javax.swing.JTextField jTextField1;
  private javax.swing.JTextField jTextField2;
  // End of variables declaration//GEN-END:variables
}
